name:                mlkem-hs
version:             0.1.0.0
github:              "arjunkhandkar/mlkem-hs"
license:             BSD-3-Clause
author:              "Arjun Khandkar"
maintainer:          "khandkararjun@gmail.com"
copyright:           "2026 Arjun Khandkar"
description:         Please see the README on GitHub at <https://github.com/githubuser/mlkem-hs#readme>

extra-source-files:
- README.md

language: GHC2021

dependencies:
- base >= 4.7 && < 5
- entropy
- memory

default-extensions:
  - CPP
  - DerivingStrategies
  - GeneralizedNewtypeDeriving

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

flags:
  mlkem512:
    manual: true
    default: false
  mlkem1024:
    manual: true
    default: false

library:
  source-dirs: src

  include-dirs:
    - cbits/mlkem-native

  c-sources:
    - cbits/mlkem-native/src/*.c
    - cbits/mlkem-native/src/fips202/*.c

  cc-options:
    - -DMLK_CONFIG_NO_RANDOMIZED_API

  when:
    - condition: flag(mlkem1024)
      cc-options: -DMLK_CONFIG_PARAMETER_SET=1024
      cpp-options: -DMLK_HS_PARAM=1024

    - condition: flag(mlkem512) && !flag(mlkem1024)
      cc-options: -DMLK_CONFIG_PARAMETER_SET=512
      cpp-options: -DMLK_HS_PARAM=512

    - condition: "!flag(mlkem512) && !flag(mlkem1024)"
      cc-options: -DMLK_CONFIG_PARAMETER_SET=768
      cpp-options: -DMLK_HS_PARAM=768

    - condition: arch(x86_64)
      c-sources:
        - cbits/mlkem-native/src/native/x86_64/src/*.c
      asm-sources:
        - cbits/mlkem-native/src/native/x86_64/src/*.S
      cc-options:
        - -mavx2
        - -mbmi2

    - condition: arch(aarch64)
      c-sources:
        - cbits/mlkem-native/src/native/aarch64/src/*.c
      asm-sources:
        - cbits/mlkem-native/src/native/aarch64/src/*.S
      cc-options:
        - -march=armv8-a+crypto

tests:
  mlkem-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mlkem-hs
